CREATE TABLE  "E_BOOK" 
   (	"CALLNO" VARCHAR(45), 
	"NAME" VARCHAR(45), 
	"AUTHOR" VARCHAR(45), 
	"PUBLISHER" VARCHAR(45), 
	"QUANTITY" NUMBER, 
	"ISSUED" NUMBER, 
	 CONSTRAINT "E_BOOK_PK" PRIMARY KEY ("CALLNO") ENABLE
   )
/
CREATE TABLE  "E_LIBRARIAN" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR(45), 
	"PASSWORD" VARCHAR(45), 
	"EMAIL" VARCHAR(45), 
	"MOBILE" NUMBER, 
	 CONSTRAINT "E_LIBRARIAN_PK" PRIMARY KEY ("ID") ENABLE
   )
/
Note: ID must be generated through sequence in E_LIBRARIAN table.

CREATE TABLE  "E_ISSUEBOOK" 
   (	"CALLNO" VARCHAR(45) NOT NULL ENABLE, 
	"STUDENTID" VARCHAR(45) NOT NULL ENABLE, 
	"STUDENTNAME" VARCHAR(45), 
	"STUDENTMOBILE" NUMBER, 
	"ISSUEDDATE" DATE, 
	"RETURNSTATUS" VARCHAR(45)
   )
/


